/**
 * Configuración declarativa de las 14 listas del artículo 69 del CFF.
 * Cabeceras verificadas contra los ficheros reales del SAT (2026-07-29).
 * Los nombres de columna van sin acentos deliberadamente: el matcher de
 * columnas (columnMatcher.ts) normaliza sin acentos en ambos lados.
 */

import { Art69ListConfig } from "./types";

const BASE =
  "https://wu1agsprosta001.blob.core.windows.net/agsc-publicaciones/Datos_abiertos";

export const ART69_LISTS: Art69ListConfig[] = [
  {
    id: "no_localizados",
    url: `${BASE}/Documents_AGR/No_localizados.csv`,
    family: "estado",
    rfcColumn: "RFC",
    nombreColumn: "RAZON SOCIAL",
    supuestoColumn: "SUPUESTO",
    fechaColumn: "FECHA DE PRIMERA PUBLICACION",
    entidadColumn: "ENTIDAD FEDERATIVA",
    esResolucion: false,
    soloAnio: false,
  },
  {
    id: "firmes",
    url: `${BASE}/Documents_AGR/Firmes.csv`,
    family: "estado",
    rfcColumn: "RFC",
    nombreColumn: "RAZON SOCIAL",
    supuestoColumn: "SUPUESTO",
    fechaColumn: "FECHA DE PRIMERA PUBLICACION",
    entidadColumn: "ENTIDAD FEDERATIVA",
    esResolucion: false,
    soloAnio: false,
  },
  {
    id: "exigibles",
    url: `${BASE}/Documents_AGR/Exigibles.csv`,
    family: "estado",
    rfcColumn: "RFC",
    nombreColumn: "RAZON SOCIAL",
    supuestoColumn: "SUPUESTO",
    fechaColumn: "FECHA DE PRIMERA PUBLICACION",
    entidadColumn: "ENTIDAD FEDERATIVA",
    esResolucion: false,
    soloAnio: false,
  },
  {
    id: "sentencias",
    url: `${BASE}/Documents_AGR/Sentencias.csv`,
    family: "estado",
    rfcColumn: "RFC",
    nombreColumn: "RAZON SOCIAL",
    supuestoColumn: "SUPUESTO",
    fechaColumn: "FECHAS DE PRIMERA PUBLICACION",
    entidadColumn: "ENTIDAD FEDERATIVA",
    esResolucion: false,
    soloAnio: false,
  },
  {
    id: "cancelados",
    url: `${BASE}/Documents_AGR/Cancelados.csv`,
    family: "evento",
    rfcColumn: "RFC",
    nombreColumn: "RAZON SOCIAL",
    supuestoColumn: "SUPUESTO",
    fechaColumn: "FECHA DE CANCELACION",
    montoColumn: "MONTO",
    entidadColumn: "ENTIDAD FEDERATIVA",
    esResolucion: true,
    soloAnio: false,
  },
  {
    id: "reduccion_art74",
    url: `${BASE}/Documents_AGR/ReduccionArt74CFF.csv`,
    family: "evento",
    rfcColumn: "RFC",
    nombreColumn: "NOMBRE, DENOMINACION O RAZON SOCIAL",
    supuestoColumn: "SUPUESTO",
    fechaColumn: "FECHA DE AUTORIZACION",
    montoColumn: "MONTO",
    entidadColumn: "ENTIDAD FEDERATIVA",
    esResolucion: false,
    soloAnio: false,
  },
  {
    id: "csd_sin_efectos",
    url: `${BASE}/Documents_AGR/CSDsinefectos.csv`,
    family: "evento",
    rfcColumn: "RFC",
    nombreColumn: "NOMBRE O RAZON SOCIAL",
    supuestoColumn: "SUPUESTO DE CANCELACION CSD",
    fechaColumn: "FECHA DE CANCELACION CSD",
    esResolucion: false,
    soloAnio: false,
  },
  {
    id: "entes_publicos",
    url: `${BASE}/Documents_AGR/EntespublicosydeGobiernoomisos.csv`,
    family: "evento",
    rfcColumn: "RFC",
    nombreColumn: "RAZON SOCIAL",
    supuestoColumn: "SUPUESTO",
    fechaColumn: "FECHA DE PRIMERA PUBLICACION",
    esResolucion: false,
    soloAnio: false,
  },
  {
    id: "condonados_146b",
    url: `${BASE}/Cifras_SAT/Indef/Condonadosart146BCFF.csv`,
    family: "evento",
    rfcColumn: "RFC",
    nombreColumn: "RAZON SOCIAL",
    supuestoColumn: "SUPUESTO",
    fechaColumn: "FECHAS DE PRIMERA PUBLICACION",
    montoColumn: "MONTO",
    entidadColumn: "ENTIDAD FEDERATIVA",
    esResolucion: true,
    soloAnio: false,
  },
  {
    id: "condonados_21",
    url: `${BASE}/Cifras_SAT/Indef/Condonadosart21CFF.csv`,
    family: "evento",
    rfcColumn: "RFC",
    nombreColumn: "RAZON SOCIAL",
    supuestoColumn: "SUPUESTO",
    fechaColumn: "FECHAS DE PRIMERA PUBLICACION",
    montoColumn: "MONTO",
    entidadColumn: "ENTIDAD FEDERATIVA",
    esResolucion: true,
    soloAnio: false,
  },
  {
    id: "condonados_decreto",
    url: `${BASE}/Cifras_SAT/Indef/CondonadosporDecreto.csv`,
    family: "evento",
    rfcColumn: "RFC",
    nombreColumn: "RAZON SOCIAL",
    supuestoColumn: "SUPUESTO",
    fechaColumn: "FECHAS DE PRIMERA PUBLICACION",
    montoColumn: "MONTO",
    entidadColumn: "ENTIDAD FEDERATIVA",
    esResolucion: true,
    soloAnio: false,
  },
  {
    id: "condonados_07_15",
    url: `${BASE}/Cifras_SAT/Indef/Condonados_07_15.csv`,
    family: "evento",
    rfcColumn: "RFC",
    nombreColumn: "Contribuyente",
    fixedSupuesto: "CONDONADOS",
    fechaColumn: "Ano",
    montoColumn: "Importe condonado",
    entidadColumn: "Entidad Federativa",
    esResolucion: true,
    soloAnio: true,
  },
  {
    id: "cancelados_07_15",
    url: `${BASE}/Cifras_SAT/Indef/Cancelados_07_15.csv`,
    family: "evento",
    rfcColumn: "RFC",
    nombreColumn: "CONTRIBUYENTE",
    fixedSupuesto: "CANCELADOS",
    fechaColumn: "ANO",
    montoColumn: "IMPORTE",
    entidadColumn: "ENTIDAD FEDERATIVA",
    esResolucion: true,
    soloAnio: true,
  },
  {
    id: "retorno_inversiones",
    url: `${BASE}/Cifras_SAT/Indef/Retornoinversiones.csv`,
    family: "evento",
    rfcColumn: "RFC",
    nombreColumn: "RAZON SOCIAL",
    supuestoColumn: "SUPUESTO",
    fechaColumn: "FECHAS DE PRIMERA PUBLICACION",
    montoColumn: "MONTO",
    entidadColumn: "ENTIDAD FEDERATIVA",
    esResolucion: true,
    soloAnio: false,
  },
];
